solve(F1,F2,F3,F4,S1,R,D,V,M,W,A,P,G,D1,H,D2,S2) :-
    Mesas = [1, 2, 3],
    member(F1,Mesas),
    member(F2,Mesas),
    member(F3,Mesas),
    member(F4,Mesas),
    member(S1,Mesas),
    member(R,Mesas),
    member(D,Mesas),
    member(V,Mesas),
    member(M,Mesas),
    member(W,Mesas),
    member(A,Mesas),
    member(P,Mesas),
    member(G,Mesas),
    member(D1,Mesas),
    member(H,Mesas),
    member(D2,Mesas),
    member(S2,Mesas),
    F1 = F2,
    F2 = F3,
    F3 = F4,
    F4 = R,
    F4 \= S1,
    D = V,
    V = M,
    W = A,
    A \= P,
    P = G,
    S1 \= D1,
    S1 \= H,
    S1 \= D2,
    S1 \= S2,
    S1 \= R,
    T is F1 + F2 + F3 + F4 + S1 + R + D + V + M + W + A + P + G + D1 + H + D2 + S2,
    T = 35.
